name: Python Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'  # Change this to your required Python version

    - name: Install dependencies
      run: |
        make install

    - name: Run application
      run: |
        make run &
        sleep 5  # Adjust the sleep duration if necessary

 
